### ISSUE TITLE
Provide seek-able interface to Client

### ISSUE THREAD

**Issue by thundergolfer** [oras-project/rust-oci-client#162]
`rust-oci-client` has `Client::pull_blob_stream` but this is not seek-able. I'm looking for a seek-able interface because it allows me to read ranges of bytes from a blob and extract a Toc (Table-of-Contents) data structure from an [eStargz](https://github.com/containerd/stargz-snapshotter/blob/main/docs/estargz.md) image.

[stargz-snapshotter](https://github.com/containerd/stargz-snapshotter) uses [containerd's](https://github.dev/containerd/containerd) seek-able `ContentStore` to achieve the same. 

We at [modal.com](https://modal.com/) are open to upstreaming this functionality if suitable :)

**Comment by thomastaylor312** [comment]
Thanks for the issue @thundergolfer! Is there any reason what you're doing couldn't be achieved with using [`StreamExt`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html) (or `TryStreamExt`) methods like `chunks` or `take`?

Using something like `AsyncSeek` wouldn't work unless we buffered into memory (because we can't go backwards in the stream)

**Comment by thundergolfer** [comment]
Thanks for the reply @thomastaylor312. I think I ultimately need an interface which will materialize arbitrary HTTP range requests against the blob and though I don't get how `chunks` would do it I think `skip` + `take` may end up working. 

I do see now that [pull_blob_response](https://github.com/oras-project/rust-oci-client/blob/8be468855f7ec133ac090c00baaa4109dde26081/src/client.rs#L1163) accepts an offset which gets stuck into a range header. So if there was just an additional `len: u64` or similar to do `bytes={offset}-{offset+len}` then I think I'd be done :)

**Comment by thomastaylor312** [comment]
Closed in #163
